name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/f0001
          git pull origin main
          export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          RAILS_ENV=production bundle install
          RAILS_ENV=production rails db:migrate
          RAILS_ENV=production rails assets:precompile
          sudo systemctl restart rails-app || RAILS_ENV=production rails server -d -b 0.0.0.0 -p 3000
        EOF

